apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-pod-reader-binding
subjects:
- kind: ServiceAccount
  name: monitor-sa
roleRef:
  kind: Role
  name: monitor-pod-reader
  apiGroup: rbac.authorization.k8s.io
